#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'auto-dock-sim-py-pkg','console_scripts','st_move'
__requires__ = 'auto-dock-sim-py-pkg'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('auto-dock-sim-py-pkg', 'console_scripts', 'st_move')()
    )
